// Generated by gencpp from file roboy_ros_face/PlayEmotionSrv.msg
// DO NOT EDIT!


#ifndef ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRV_H
#define ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRV_H

#include <ros/service_traits.h>


#include <roboy_ros_face/PlayEmotionSrvRequest.h>
#include <roboy_ros_face/PlayEmotionSrvResponse.h>


namespace roboy_ros_face
{

struct PlayEmotionSrv
{

typedef PlayEmotionSrvRequest Request;
typedef PlayEmotionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlayEmotionSrv
} // namespace roboy_ros_face


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_ros_face::PlayEmotionSrv > {
  static const char* value()
  {
    return "af358f0eedfa2bb2933016410b2c78ee";
  }

  static const char* value(const ::roboy_ros_face::PlayEmotionSrv&) { return value(); }
};

template<>
struct DataType< ::roboy_ros_face::PlayEmotionSrv > {
  static const char* value()
  {
    return "roboy_ros_face/PlayEmotionSrv";
  }

  static const char* value(const ::roboy_ros_face::PlayEmotionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_ros_face::PlayEmotionSrvRequest> should match 
// service_traits::MD5Sum< ::roboy_ros_face::PlayEmotionSrv > 
template<>
struct MD5Sum< ::roboy_ros_face::PlayEmotionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_ros_face::PlayEmotionSrv >::value();
  }
  static const char* value(const ::roboy_ros_face::PlayEmotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_ros_face::PlayEmotionSrvRequest> should match 
// service_traits::DataType< ::roboy_ros_face::PlayEmotionSrv > 
template<>
struct DataType< ::roboy_ros_face::PlayEmotionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_ros_face::PlayEmotionSrv >::value();
  }
  static const char* value(const ::roboy_ros_face::PlayEmotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_ros_face::PlayEmotionSrvResponse> should match 
// service_traits::MD5Sum< ::roboy_ros_face::PlayEmotionSrv > 
template<>
struct MD5Sum< ::roboy_ros_face::PlayEmotionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_ros_face::PlayEmotionSrv >::value();
  }
  static const char* value(const ::roboy_ros_face::PlayEmotionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_ros_face::PlayEmotionSrvResponse> should match 
// service_traits::DataType< ::roboy_ros_face::PlayEmotionSrv > 
template<>
struct DataType< ::roboy_ros_face::PlayEmotionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_ros_face::PlayEmotionSrv >::value();
  }
  static const char* value(const ::roboy_ros_face::PlayEmotionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRV_H
