// Generated by gencpp from file roboy_ros_face/PlayEmotionSrvResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRVRESPONSE_H
#define ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_ros_face
{
template <class ContainerAllocator>
struct PlayEmotionSrvResponse_
{
  typedef PlayEmotionSrvResponse_<ContainerAllocator> Type;

  PlayEmotionSrvResponse_()
    {
    }
  PlayEmotionSrvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlayEmotionSrvResponse_

typedef ::roboy_ros_face::PlayEmotionSrvResponse_<std::allocator<void> > PlayEmotionSrvResponse;

typedef boost::shared_ptr< ::roboy_ros_face::PlayEmotionSrvResponse > PlayEmotionSrvResponsePtr;
typedef boost::shared_ptr< ::roboy_ros_face::PlayEmotionSrvResponse const> PlayEmotionSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_ros_face

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_ros_face/PlayEmotionSrvResponse";
  }

  static const char* value(const ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayEmotionSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roboy_ros_face::PlayEmotionSrvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_ROS_FACE_MESSAGE_PLAYEMOTIONSRVRESPONSE_H
